### ISSUE TITLE
Reactions not working properly.

### ISSUE THREAD

**Issue by DetectiveHuman** [DetectiveHuman/discord-poll-bot#1]
Fix reactions.

**Comment by 1Pockyninja1** [comment]
In order to react to embeds the emojis need to be stored into an array.
Here's an example by Kati3e:
Refer to line 71.
https://github.com/Kati3e/KatBot-Discord/blob/master/commands/polls/poll.js

**Comment by RailRunner16** [comment]
i fixed it in a PR, @DetectiveHuman, enjoy!

**Comment by DetectiveHuman** [comment]
oof ty

**Comment by DetectiveHuman** [comment]
Fixed.
